config/routes.rb
Rails.application.routes.draw do

  get 'carriers/data', :defaults => { :format => 'json' }
  get 'carriers/usData', :defaults => { :format => 'json' }
  resources :technical_reports, only: [:index]
  resources :carriers, only: [:index, :show, :data, :usData]

  root "home#index"

end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
  validates_uniqueness_of :name

  def num_delayed_flights_data

    data = [
      {
          value: (self.num_flights - (self.num_cancelled_flights + self.num_delayed_flights)),
          color:"#5B9632",
          highlight: "#85BC5E",
          label: "Normal flights"
      },
      {
          value: self.num_cancelled_flights,
          color: "#74132D",
          highlight: "#9A334F",
          label: "Cancelled flights"
      },
      {
          value: self.num_delayed_flights,
          color: "#AA9339",
          highlight: "#D4BF6A",
          label: "Delayed flights"
      }
    ]
    data
  end

  def delay_time_data
    data = {
    labels: ["Delays", "Cancellations"],
    datasets: [
        {
            label: "Mean delay and cancellation times",
            fillColor: "rgba(240,95,64,0.5)",
            strokeColor: "rgba(240,95,64,0.8)",
            highlightFill: "rgba(240,95,64,0.75)",
            highlightStroke: "rgba(240,95,64,1)",
            data: [self.mean_delay_time.round(2), self.mean_ground_time_cancelled_flights.round(2)]
        },

    ]
};

  end

  def self.assign_city_markets(carrier)
    data = {
      "type" => "FeatureCollection",
      "features" => []
    }
    cities = Flight.show_city_markets(carrier.name)
    cities.each do |city|
      city_market = CityMarket.find_by(name: city)
      if city_market
        city_data = {
          "type": "Feature",
          "id": city_market[:id].to_s,
          "geometry": {
            "type": "Point",
            "coordinates":[-(city_market[:longitude]), city_market[:latitude]]
          },
          "properties": {
            "name": city_market[:name],
            "population": city_market[:population]
          }
        }
        data["features"] << city_data
      end
    end
    data
  end

  def self.assign_populations
    carriers = Carrier.all
    carriers.each do |carrier|
      pop = 0
      cities = Flight.show_city_markets(carrier.name)
      cities.each do |city|
        city_market = CityMarket.find_by(name: city)
        if city_market
          pop += city_market[:population]
        end
      end
      carrier[:population] = pop
      carrier.save
    end
  end

end

app/models/city_market.rb
class CityMarket < ActiveRecord::Base
end

app/models/flight.rb
class Flight < ActiveRecord::Base


  def self.carrier_names
    Flight.pluck(:carrier).uniq.sort
  end

  def self.carrier_database
    carriers = Flight.carrier_names
    carriers.each do |name|
      properties = Flight.get_properties(name)
      carrier = Carrier.find_by(name: name)
      carrier.update(properties)
    end
  end

  def self.get_properties(name)
    properties = {}
    properties[:num_flights] = Flight.num_flights(name)
    properties[:num_cancelled_flights] = Flight.num_cancelled_flights(name)
    properties[:mean_ground_time_cancelled_flights] = Flight.mean_ground_time_cancelled_flights(name)
    properties[:num_delayed_flights] = Flight.num_delayed_flights(name)
    properties[:mean_delay_time] = Flight.mean_delay_time(name)
    properties[:standard_deviation] = Flight.standard_deviation(name)
    properties
  end

  def self.show_city_markets(carrier_name)
    markets = Flight.where(carrier: carrier_name).pluck(:dest_city_market, :origin_city_market).uniq
    markets.flatten!.uniq!
  end

  def self.num_flights(carrier_name)
    Flight.where(carrier: carrier_name).pluck(:id).length
  end

  def self.cancelled_flights(carrier_name)
    Flight.where(carrier: carrier_name).where(cancelled: true).where('cancellation_code = ?', "Carrier").pluck(:total_add_g_time)
  end

  def self.num_cancelled_flights(carrier_name)
    Flight.cancelled_flights(carrier_name).length
  end

  def self.mean_ground_time_cancelled_flights(carrier_name)
    cancellations = Flight.cancelled_flights(carrier_name).compact
    Flight.mean(cancellations)
  end

  def self.delayed_flights(carrier_name)
    Flight.where(carrier: carrier_name).where('carrier_delay > 0').pluck(:carrier_delay)
  end

  def self.num_delayed_flights(carrier_name)
    Flight.delayed_flights(carrier_name).length
  end

  def self.mean_delay_time(carrier_name)
    delays = Flight.delayed_flights(carrier_name)
    Flight.mean(delays)
  end

  def self.mean(array)
    array.inject(0) { |sum, x| sum += x } / array.size.to_f
  end

  def self.standard_deviation(carrier_name)
    delays = Flight.delayed_flights(carrier_name)
    deviances = delays.map do |delay|
      delay * delay
    end
    mean = Flight.mean(deviances)
    Math.sqrt(mean).round(2)
  end

  def self.flights_per_carrier_chart_data
    data = []
    Carrier.all.each do |carrier|
      data << {
        value: carrier.num_flights,
        color: carrier.colour,
        highlight: carrier.colour,
        label: carrier.name
      }
    end
    data
  end

  def self.flights_per_carrier_chart_options
    options = {
      animationEasing: "easeInCubic",
      width: 350,
      height: 350
    }
    options
  end

  def self.number_of_destinations_data
    data = {
      labels: [],
      datasets: [{
          label: "Number of destinations served by each carrier",
          fillColor: "rgba(240,95,64,0.5)",
          strokeColor: "rgba(240,95,64,0.8)",
          highlightFill: "rgba(240,95,64,0.75)",
          highlightStroke: "rgba(240,95,64,1)",
          data: []
        }]
      }
    Carrier.all.each do |carrier|
      data[:labels] << carrier.name
      total = 0
      markets = Flight.show_city_markets(carrier.name).length
      total += markets
      data[:datasets][0][:data] << total
    end
    data
  end

end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :origin_city_market, class_name: "CityMarket"
  belongs_to :dest_city_market, class_name: "CityMarket"
  belongs_to :carrier
end

app/models/technical_report.rb
class TechnicalReport < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController



  def index
    @carriers = Carrier.all
  end

  def show
    @carrier = Carrier.find(params[:id])
    @flights = Flight.where(carrier: @carrier.name)
    @metros = Flight.show_city_markets(@carrier.name)
    @flight_breakdown_data = @carrier.num_delayed_flights_data
    @flight_delay_data = @carrier.delay_time_data
    @metro_data = Carrier.assign_city_markets(@carrier)
  end

  def data
    @carrier = Carrier.find(params["id"].to_i)
    respond_to do |format|
      format.json {
        render :json => Carrier.assign_city_markets(@carrier)
      }
    end
  end

  def usData
    @data = File.read("public/us.json")
    respond_to do |format|
      format.json {
        render :json => @data
      }
    end
  end

end

app/controllers/city_markets_controller.rb
class CityMarketsController < ApplicationController



end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @carriers = Carrier.all
    @total_flight_data = Flight.flights_per_carrier_chart_data
    @total_flight_options = Flight.flights_per_carrier_chart_options
    @number_of_destinations = Flight.number_of_destinations_data
  end

end

app/controllers/technical_reports_controller.rb
class TechnicalReportsController < ApplicationController

  def index
    @carriers = Carrier.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/technical_reports_helper.rb
module TechnicalReportsHelper
end

app/views/carriers/_carriers.html.erb
<div class="row text-center">
  <div class="col-lg-4"></div>
  <div class="col-lg-4 carriers-list">
      <% @carriers.each do |carrier| %>
        <% if carrier.analyzed %>
          <h4><%= link_to carrier.name, carrier %></h4>
        <% end %>
      <% end %>
  </div>
  <div class="col-lg-4"></div>
</div>

app/views/carriers/_comparison.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h2 class="section-heading">Quick comparison</h2>
      <hr class="primary">
      <p>Click on a column header to rank the carriers by that column.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <table id="carrierTable" class="tablesorter table">
      <thead>
        <tr class="text-center">
          <th>Name</th>
          <th>Flights</th>
          <th>Population served</th>
          <th>Cancelled flight rate</th>
          <th>Delayed flight rate</th>
          <th>Mean delay time</th>
          <th>Std dev</th>
          <th>Delay per 1000 flights</th>
        </tr>
      </thead>
      <tbody>
        <% @carriers.each do |carrier| %>
          <% if (carrier.analyzed == true) %>
            <tr>
              <td><%= carrier.name %></td>
              <td><%= carrier.num_flights %></td>
              <td><%= carrier.population %></td>
              <td><%= ((carrier.num_cancelled_flights.to_f / carrier.num_flights.to_f) * 1000).round(2) %> times per 1000</td>
              <td><%= ((carrier.num_delayed_flights.to_f / carrier.num_flights.to_f) * 1000).round(2) %> times per 1000</td>
              <td><%= carrier.mean_delay_time.round(2) %> minutes</td>
              <td><%= carrier.standard_deviation.round(2) %></td>
              <td><%= (((carrier.num_delayed_flights.to_f / carrier.num_flights.to_f) * 1000).round(2) * carrier.mean_delay_time.to_f).round(2) %> minutes</td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 text-center" id="metro-compare">
      <br>
      <h2 class="section-heading">City markets served</h2>
      <hr class="primary">
      <p>Click on a carrier to see a map of the city markets it serves.</p>
      <p>
        <% @carriers.each do |carrier| %>
          <% if (carrier.analyzed == true) %>
            <a href="" class="carrier-map" <%= "data-params-id=#{carrier.id}" %>><%= carrier.name %></a> |
          <% end %>
        <% end %>
      <p>
    </div>
  </div>
</div>

app/views/carriers/index.html.erb
   <header class="carriers">
    <div class="header-content">
      <div class="header-content-inner">
        <br><br><br>
        <h1 style="font-size: 65px;">Carriers</h1>
        <hr>
        <p style="font-size: 22px;">After narrowing down the selection to relevant carriers, five airlines were analyzed in depth. Insights on each can be found by clicking on each below. A quick comparison can be found below the list.</p>
        </div>
            <%= render "carriers/carriers" %>
    </div>
  </header>
  <section>

      <%= render "carriers/comparison" %>

  </section>

app/views/carriers/show.html.erb
<section class="bg-primary" id="about">
  <div class="container">
      <div class="row">
          <div class="col-lg-8 col-lg-offset-2 text-center">
              <h2 class="section-heading"><%= @carrier.name %></h2>
              <hr class="light">

              <p class="text-faded">Total number of flights: <%= number_with_delimiter(@carrier.num_flights, :delimiter => ',') %> </p>
              <p class="text-faded">Number of cancelled flights: <%= number_with_delimiter(@carrier.num_cancelled_flights, :delimiter => ',') %> | Cancellation rate: <%= ((@carrier.num_cancelled_flights.to_f / @carrier.num_flights.to_f) * 1000).round(2) %> times per 1000 flights</p>
              <p class="text-faded">Number of delayed flights: <%= number_with_delimiter(@carrier.num_delayed_flights, :delimiter => ',') %> | Delayed rate: <%= ((@carrier.num_delayed_flights.to_f / @carrier.num_flights.to_f) * 1000).round(2) %> times per 1000 flights</p>
              <p class="text-faded">Number of metropolitan areas served: <%= @metros.length %> | Total population served: <%= number_with_delimiter(@carrier.population, :delimiter => ',') %></p>
          </div>
      </div>
  </div>
</section>
<section>
  <div class="container">
    <div class="row">
      <div class="col-lg-1"></div>
      <div class="col-lg-5 text-center">
        <h3>Number of on-time, delayed, and cancelled flights</h3>
        <%= chartjs_pie_chart @flight_breakdown_data %>
      </div>
      <div class="col-lg-5 text-center">
        <h3>Mean times of delays and cancellations (minutes)</h3>
        <%= chartjs_bar_chart @flight_delay_data %>
      </div>
      <div class="col-lg-2"></div>
    </div>
    <div class="row">
      <div class="col-lg-12 text-center" id="metro-map" <%= "data-params-id=#{params[:id]}" if params.has_key?(:id) %>>
        <h3>Metropolitan areas served: <%= @metros.length %> | Population served: <%= number_with_delimiter(@carrier.population, :delimiter => ',') %></h3>
      </div>
    </div>
  </div>
</section>

app/views/home/_header.html.erb
<header>
  <div class="header-content">
    <div class="header-content-inner">
      <br><br><br>
      <h1 style="font-size: 65px;">Choosing a primary carrier through data analysis</h1>
      <hr>
      <p style="font-size: 22px;">Imagine you're a company trying to choose a primary airline. Your main concern is punctuality - which carrier is the best at staying on schedule? This site presents an analysis of a sample set of data for airline performance, and makes a recommendation on which carrier you should choose.</p>
      <p style="font-size: 22px;">Scroll down to get started, or skip to the analysis of specific carriers and technical write-up via the navbar above.</p>
      </div>
  </div>
</header>

app/views/home/_modals.html.erb
<!-- Modal -->
<div class="modal fade" id="nycmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New York is king</h4>
      </div>
      <div class="modal-body">
        <p>This analysis only looked at flights to and from the NYC Metropolitan Area. It took the assumption that a company would be concerned with the flights to and from its headquarters. New York City was chosen as the location for these headquarters as a major metropolitan area with numerous airports and flights.
        </p>
        <p>To select these flights from the dataset, the OriginCityMarket and DestCityMarket fields were examined to find flights where the value was the NYC Metropolitan Area.</p>
        <p>This analysis is unable to account for delays that might occur on the subsequent parts of multi-leg journeys. It is safe to assume that the majority of travel undertaken by the company in the USA will be non-stop trips.</p>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="control" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Ignore the uncontrollable</h4>
      </div>
      <div class="modal-body">
        <p>The following fields were deemed to be entirely beyond the control of the carriers, and therefore not pertinent to this analysis:</p>
        <ul>
          <li>Delays from the National Air System (NASDelay)</li>
          <li>Delays from airport security issues (SecurityDelay)</li>
        </ul>
        <p>Along the same lines, cancelled flights were filtered to exclude from consideration those with the following  codes:</p>
        <ul>
          <li>Weather</li>
          <li>National Air System</li>
        </ul>
        <p>Additionally, the LateAircraftDelay field was dropped as well. This delay indicates that the plane was delayed because of delays in its previous flight. The dataset does not keep track of the reason for this delay, and as such it is impossible to determine whether it was the fault of the carrier or not.</p>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="time" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Bigger is better</h4>
      </div>
      <div class="modal-body">
        <p>The following fields were not considered in this analysis:</p>
        <ul>
          <li>Year</li>
          <li>Quarter</li>
        </ul>
        <p>These fields were removed from the dataset to improve performance when querying the database.</p>
      </div>
    </div>
  </div>
</div>

app/views/home/_step1.html.erb
<section class="bg-primary" id="start">
  <div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 text-center">
          <h2 class="section-heading">Step 1: Importing the data</h2>
          <hr class="light">
          <p class="text-faded">This excercise uses a dataset consisting of all flights in the USA from September to November of 2012, as taken from the <a href="http://www.transtats.bts.gov/Fields.asp?Table_ID=236" target="_blank">Bureau of Transportation Statistics On-Time Performance dataset.</a> The dataset contains a variet of indicators related to the on-time performance of each flight.</p>
          <p class="text-faded">As an initial step, this dataset (consisting of 1,491,146 individual flights) was imported into a database that is the basis of this site's analysis.</p>
        </div>
    </div>
   </div>
</section>

app/views/home/_step2.html.erb
<section>
  <div class="container" id="step2">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2 class="section-heading">Step 2: Selecting the relevant data</h2>
            <hr class="primary">
            <p></p>
        </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x  fa-apple text-primary" style="visibility: visible; animation-name: bounceIn;"></i>
          <h3>Home is king</h3>
          <p class="text-muted">For this exercise, let's assume your company is based in New York City. Given this, it makes sense to only examine those flights with an origin or destination of the NYC Metropolitan area.</p>
          <br>
          <p class="text-muted">Applying this criteria, roughly 89% of the flights in the dataset can be disregarded. This reduces the number of flights to consider to 167,716.</p>
          <br>
          <button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#nycmodal">
            Learn more
          </button>
          <br>
        </div>
      </div>

      <div class="col-lg-4 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-bolt text-primary" style="visibility: visible; animation-name: bounceIn;"></i>
          <h3>Ignore the uncontrollable</h3>
          <p class="text-muted">Flights are often delayed or cancelled because of factors outside the control of the carriers. These factors are tracked in the dataset, and include bad weather, airport security, and National Air System considerations.</p>
          <br>
          <p class="text-muted">For this analysis, it can be assumed that these factors affect all carriers equally and, as such, can be ignored.</p>
          <br>
          <button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#control">
            Learn more
          </button>
          <br>
        </div>
      </div>

      <div class="col-lg-4 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-calendar text-primary" style="visibility: visible; animation-name: bounceIn;"></i>
          <h3>Short timeframe</h3>
          <p class="text-muted">The dataset of flights only covers 3 months. As such, a number of time-sensitive considerations were ignored, including whether a carrier performed better across seasons.</p>
          <br>
          <p class="text-muted">Similarly, this assessment assumes that three months is too short a period to assess whether any carrier is demonstrating sustainable trends in improving its performance.</p>
          <br>
          <button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#time">
            Learn more
          </button>
        </div>
    </div>
  </div>
</section>

app/views/home/_step4.html.erb
<section id="comparison">
  <div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 text-center">
          <h2 class="section-heading">Step 4: Comparing the remaining carriers</h2>
          <hr class="primary">
          <p>At this point, only five carriers remain as a viable primary carrier. Insights on each carrier can be reached by clicking on its name.</p>
        </div>
    </div>
    <div>
      <%= render "carriers/carriers" %>
    </div>
   </div>
   <div>
    <br><br>
    <%= render "carriers/comparison" %>
   </div>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carrier Selector</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <script src="https://d3js.org/d3.v3.min.js" charset="utf-8"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
  <script src="//d3js.org/topojson.v1.min.js"></script>
  <script src="//d3js.org/queue.v1.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>

  <%= csrf_meta_tags %>
</head>
<body id="page-top" class="<%= controller_name %> <%= action_name %>">
  <nav id="mainNav" class="navbar navbar-default navbar-fixed-top affix">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "Home", root_path, class: "navbar-brand page-scroll"%>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Carrier Comparison", carriers_path %>

          </li>
          <li>
            <%= link_to "Technical Report", technical_reports_path %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<%= yield %>

<section id="contact">
  <div class="container">
      <div class="row">
          <div class="col-lg-8 col-lg-offset-2 text-center">
              <h2 class="section-heading">Data excercise by Andrew Reid</h2>
              <hr class="primary">
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12 text-center">
              <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s" style="visibility: visible; animation-delay: 0.1s; animation-name: bounceIn;"></i>
              <p><a href="mailto:s.andrew.reid@gmail.com">s.andrew.reid@gmail.com</a></p>
          </div>
      </div>
  </div>
</section>
</body>
</html>

app/views/technical_reports/index.html.erb
<header class="carriers">
  <div class="header-content carriers">
    <div class="header-content-inner carrieres">
      <br><br><br>
      <h1 style="font-size: 65px;">Technical Write-up</h1>
      <hr>
      <br>
      <p style="font-size: 22px;">This page provides a technical write-up of the hypotheses, methodology and analysis undertaken in this data excercise. It will also highlight limitations to the approach, as well as avenues for further exploration.</p>
      <p style="font-size: 22px;">Where helpful, it will link to charts and tables rendered elsewhere in the Webapp.</p>
      <p>The source code for this project is available on <a href="https://github.com/sareid/carrier-selector" target="_blank"><i class="fa fa-4x fa-github" style="color: white"></i></a></p>
      <br><br>
      </div>
  </div>
</header>
<section class="bg-primary" id="start">
    <div class="container">
      <div class="row">
          <div class="col-lg-8 col-lg-offset-2 text-center">
            <h2 class="section-heading">Hypothesis</h2>
            <hr class="light">
            <p class="text-faded">Based on the dataset provided, it would appear that Delta Air Lines is the best pick as a primary carrier. This reflects both the high number of flights operated by Delta Airlines, its service to 36 metropolitan areas across the US (representing the largest population served of any carrier), and the comparatively low frequency of delayed and cancelled flights. Specific figures for this can be seen in the comparison below, as well as on the <%= link_to "the more in depth carrier comparison pages", carriers_path %></p>
          </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <%= render "carriers/comparison" %>
        </div>
      </div>
     </div>
  </section>
  <section id="services">
    <div class="container">
      <div class="row">
        <div class="col-lg-10 col-lg-offset-1">
          <h2 class="section-heading text-center">Methodology</h2>
          <hr class="primary">
          <p>This data excercsise was completed using a Ruby on Rails webapp, that used the ActiveRecord pattern of object relational mapping to query a Postgres database. On the front-end, visualizations and design were achieved through D3, ChartJS, jQuery and Bootstrap.</p>
          <p>The original CSV file with the dataset was imported into a a PostgreSQL database via pgAdmin3. At this point the number of entries in the database produced performance issues when running queries via the ActiveRecord pattern. Under the assumption that the analysis would be best focused on flights to and from a specific area (in this case the New York Metropolitan Area), the database was cleared of all entries save those with a 'DestCityMarket' or 'OriginCityMarket' field with a value of "New York, NY (Metropolitan Area)". This reduced the number of entries from 1,491,146 to 167,716, eliminating most database performance issues.</p>
          <p>To further help with querying issues, a separate Carrier model was built in Rails, with properties that were populated by queries to the main database. These properties included important figures for analyis, such as total number of flights, number of delayed flights, number of cancelled flights, mean time of delays, and total population served.</p>
          <p>As a carrier with many flights to many locations can assumbed to be preferable, methods were written to query the database for both the number of flights operated by a certain carrier, and the metropolitan areas served by that carrier. After visualizing the result (as seen on the <%= link_to "summary page", root_path %>), it was clear that many carriers would not be worth analyzing. The reasons for this were as follows:</p>
          <ul>
            <li>Frontier Airlines, Hawaiian Airlines, Mesa Airlines, SkyWest Airlines, and Alaska Airlines only flew between New York and one other metropolitan area. Additionally (and in part because of this), they only provided a small percentage of the total flights of the other carriers.</li>
            <li>Virgin America flew to more metropolitan areas than the carriers mentioned above, but had the fewest total number of flights</li>
            <li>US Airways and Southwest Airlines had more flights and serviced more metropolitan areas than the carriers mentioned above, but still had far fewer flights and destinations in comparison to the remaining five to be a credible candidate as a primary carrier</li>
          </ul>
          <p>For the remaining five carriers, comparisons were made using the information on delays and cancellations. The analysis focused on indicators deemed to be witin the carrier's control - eg: entries in the 'CarrierDelay' field. It was assumed that delays to weather, airport security, and National Air System factors applied equally to all carriers. Delays from late aircraft were also ignored, because it was impossible to determine whether this delay was the carrier's fault or not.<p>
          <p>Pie charts were rendered for each carrier showing the breakdown of on-time, delayed, and cancelled flights, alongside bar charts visualizing the mean time for delays and time on the ground during cancellations. To account for the different total number of flights, the rate of delayed and cancelled flights per 1000 flights were calculated, as well as the total amount of time lost to delay per 1000 flights. Based on these statistics, Delta Air Lines was deemed to be the carrier with the best on time performance.</p>
          <p>To further assist with visualising the breadth of service provided by each carrier, bubble maps of the city markets served were rendered in D3. This provided an immediate overview not only of the distribution of city markets across the US, but also the size of these markets (with larger populations represented by larger bubbles). This visualisation revealed that ExpressJet, while servicing the largest number of city markets, only serviced those on the East Coast, making them less desirable.</p>
        </div>
      </div>
    </div>
  </section>
  <section class="bg-primary" id="start">
    <div class="container">
      <div class="row">
          <div class="col-lg-10 col-lg-offset-1 ">
            <h2 class="section-heading text-center">Limitations and future research</h2>
            <hr class="light">
            <p>The methodology used in this analysis has several limitations. These include:</p>
            <ul>
              <li>Price not taken into account: This would be a critical factor for any company looking to choose a primary carrier. It was not immediately apparent how the prices for these specific flights could be accounted for. Perhaps a process of scraping online prices along key routes to monitor mean prices over a period of time could provide some insights.</li>
              <li>Daily variations: There may be days of the week that a company's employees are more likely to travel (e.g. Monday and Friday). With the data available delay and cancellation information could have been calculated on a daily basis to see if any airline was markedly better during these times. This was not integrated due to time constraints.</li>
            </ul>
          </div>
      </div>
  </section>